# Release the library to various npm repositories
name: Release library

on:
  release:
    types: [released]

jobs:
  build-release:
    name: Build release
    uses: ./.github/workflows/build.yml
    with:
      node-version: 18

  publish-npm:
    needs: build-release
    uses: ./.github/workflows/npm-publish.yml
    with:
      registry-url: https://registry.npmjs.org/
      node-version: 18
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build-release
    uses: ./.github/workflows/npm-publish.yml
    with:
      registry-url: https://npm.pkg.github.com/
      node-version: 18
    secrets:
      npm-token: ${{ secrets.GITHUB_TOKEN }}
